POST {{BASE_URL}}/{{API_VERSION}}/order HTTP/1.1
Content-Type: application/json

{
  "show":["64e51712872724e7defa791b"],
  "shippingAddress": {"country": "israel", "postalCode": 7913000, "city": "ashkelon", "address": "hotza kibutz"},
  "paymentMethod": "PayPal",
  "ticketsAmounts": 2,
  "itemsPrice": 110,
  "taxPrice": 10
}
###
# @name update_order_to_paid
PUT {{BASE_URL}}/{{API_VERSION}}/order/653c1fc01f30628723b0c090/paid HTTP/1.1
Content-Type: application/json

{
  "payment": {
    "id": 123,
    "status": "paid",
    "update_time": 12314135,
    "payer": {"email_address": "foo@mail.com"}}
}
###
PUT {{BASE_URL}}/{{API_VERSION}}/order/123/delivered HTTP/1.1
Content-Type: application/json

{
}
###
GET {{BASE_URL}}/{{API_VERSION}}/order/myorders HTTP/1.1
Content-Type: application/json

{
}
###
GET {{BASE_URL}}/{{API_VERSION}}/order/653cd8c2516f9cc6a17e5941 HTTP/1.1
Content-Type: application/json

{
}
###
# @name get_paypal_client__id
GET {{BASE_URL}}/config/paypal HTTP/1.1