////////     profile routes:    ////////
GET {{BASE_URL}}/{{API_VERSION}}/user/profile HTTP/1.1
###

PUT {{BASE_URL}}/{{API_VERSION}}/user/profile HTTP/1.1
Content-Type: application/json

{
  "name": "{{NAME}}",
  "email": "{{BUYER_EMAIL}}",
  "password": "{{password_1}}"
}
###


///    login logout routes:      //////
# @name adminLogin
POST {{BASE_URL}}/{{API_VERSION}}/user/login HTTP/1.1 HTTP/1.1
Content-Type: application/json

{
  "email": "{{EMAIL}}",
  "password": "{{password_1}}"
}
###

# @name buyerLogin
POST {{BASE_URL}}/{{API_VERSION}}/user/login HTTP/1.1 HTTP/1.1
Content-Type: application/json

{
  "email": "{{BUYER_EMAIL}}",
  "password": "{{password_1}}"
}
###

# @name logout
POST {{BASE_URL}}/{{API_VERSION}}/user/logout HTTP/1.1
###